---
title: "R Notebook"
output: html_notebook
---


```{r}
list.files()
```

```{r}

library(readxl)

data_paper <- read_xlsx("data_paper.xlsx")
data_paper <- as.data.frame(data_paper)
data_paper

```




#Membuat Distribusi Jumlah Artikel berdasarkan Jurnal
```{r}


library(dplyr)

grup <- group_by(data_paper, `Nama Jurnal`, ISSN)

data_jurnal <- grup %>% summarise(
		freq = n()

)

data_jurnal <- as.data.frame(data_jurnal)

colnames(data_jurnal) = c("Journal", "ISSN", "Number of Articles in Our Database")

data_jurnal
```
























#Jumlah Keywords
```{r}

ambil_keyword <- data_paper[,"Keyword"]
ambil_keyword <- as.data.frame(ambil_keyword)

simpan_keyword <- vector(mode = "character")
  
  
for(i in 1 :  length(ambil_keyword[,1])  )
{
  
  X <- ambil_keyword[i,1]
  
  X <- tolower(X) #mengubah menjadi huruf kecil

      
      X <- unlist(strsplit(as.character(X), "  ;", fixed = TRUE))
      X <- unlist(strsplit(as.character(X), " ;", fixed = TRUE))
      X <- unlist(strsplit(as.character(X), ";  ", fixed = TRUE))
      X <- unlist(strsplit(as.character(X), "; ", fixed = TRUE))
      X <- unlist(strsplit(as.character(X), ";", fixed = TRUE))
      #X <- unlist(strsplit(as.character(X), ", ", fixed = TRUE))
      #  X <- unlist(strsplit(as.character(X), "  ,", fixed = TRUE))
           # X <- unlist(strsplit(as.character(X), " ,", fixed = TRUE))
           # X <- unlist(strsplit(as.character(X), ",", fixed = TRUE))
      
      simpan_keyword = c(simpan_keyword, X)
      
      
  
  
}



level_simpan_keyword <- as.factor(simpan_keyword)

level_simpan_keyword <- levels(level_simpan_keyword)

length(level_simpan_keyword)


level_simpan_keyword
```














#Jumlah Subject
```{r}

ambil_scope <- data_paper[,"Scope"]
ambil_scope <- as.data.frame(ambil_scope)

simpan_scope <- vector(mode = "character")
  
  
for(i in 1 :  length(ambil_scope[,1])  )
{
  
  X <- ambil_scope[i,1]
  
  X <- tolower(X) #mengubah menjadi huruf kecil

      
      X <- unlist(strsplit(as.character(X), "  ;", fixed = TRUE))
      X <- unlist(strsplit(as.character(X), " ;", fixed = TRUE))
      X <- unlist(strsplit(as.character(X), ";  ", fixed = TRUE))
      X <- unlist(strsplit(as.character(X), "; ", fixed = TRUE))
      X <- unlist(strsplit(as.character(X), ";", fixed = TRUE))
      #X <- unlist(strsplit(as.character(X), ", ", fixed = TRUE))
      #  X <- unlist(strsplit(as.character(X), "  ,", fixed = TRUE))
           # X <- unlist(strsplit(as.character(X), " ,", fixed = TRUE))
           # X <- unlist(strsplit(as.character(X), ",", fixed = TRUE))
      
      simpan_scope = c(simpan_scope, X)
      
      
  
  
}



level_simpan_scope <- as.factor(simpan_scope)

level_simpan_scope <- levels(level_simpan_scope)

length(level_simpan_scope)


level_simpan_scope
```










```{r}

library(dplyr)
library(tidytext)
library(widyr)


data_tes <- data_paper[c("No", "Judul Artikel")]

data_tes
```




```{r}

 nasa_title <- data_frame( id = data_tes$No, title = data_tes$`Judul Artikel`)

 nasa_title

```










```{r}

nasa_desc <- data_frame(id = data_paper$No, desc = data_paper$Keyword)
 
nasa_desc %>%
 select(desc) %>%
 sample_n(5)

```




```{r}
 library(tidyr)
 nasa_keyword <- data_frame(id = data_paper$No, keyword = data_paper$Keyword) %>% unnest(keyword)

 nasa_keyword

```






```{r}
 library(tidytext)
 nasa_keyword <- data_frame(id = data_paper$No, keyword = data_paper$Keyword) %>% unnest(keyword)

 nasa_keyword <-  nasa_keyword %>%  unnest_tokens(word, keyword) %>%  anti_join(stop_words)
 
 nasa_keyword


```



```{r}
 nasa_keyword %>%
 count(word, sort = TRUE)

```







```{r}
 library(tidytext)
 nasa_title <- data_frame( id = data_tes$No, title = data_tes$`Judul Artikel`)
 nasa_title <- nasa_title %>%  unnest_tokens(word, title) %>%  anti_join(stop_words)
 
 nasa_title


```







```{r}
 nasa_title %>%
 count(word, sort = TRUE)

```




```{r}
my_stopwords <- data_frame(word = c(as.character(1:2),
 "role", "students"))



 nasa_title <- data_frame( id = data_tes$No, title = data_tes$`Judul Artikel`)
 nasa_title <- nasa_title %>%  unnest_tokens(word, title) %>%  anti_join(stop_words)
 
 nasa_title %>%
 count(word, sort = TRUE)
 



```


```{r}

nasa_title <- nasa_title %>%
 anti_join(my_stopwords)


nasa_title


 nasa_title %>%
 count(word, sort = TRUE)
 
```



```{r}

 library(widyr)
 title_word_pairs <- nasa_title %>%
 pairwise_count(word, id, sort = TRUE, upper = FALSE)
 title_word_pairs

```





```{r}
library(ggplot2)
 library(igraph)
 library(ggraph)

 set.seed(1234)
 title_word_pairs %>%
  filter(n >= 7) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = n, edge_width = n), edge_colour = "cyan4") +
  geom_node_point(size = 5) +
  geom_node_text(aes(label = name), repel = TRUE,
                 point.padding = unit(0.2, "lines")) +
  theme_void()
 
 
```












```{r}

data_keyword <- data_paper[c("Keyword")]
data_keyword2 <- data_keyword

for(i in 1 : length(data_keyword[,1]))
{
  
  x <- data_keyword[i,1]
  
    simpan_keyword_hapus_spasi <- gsub(" ", "", x)
    simpan_keyword_hapus_spasi <- gsub("-", "", simpan_keyword_hapus_spasi)
    simpan_keyword_hapus_spasi <- gsub("'", "", simpan_keyword_hapus_spasi)
    
    data_keyword2[i,1] = simpan_keyword_hapus_spasi
    
    
  
  
}


data_keyword2
```





```{r}
 library(tidytext)
 nasa_keyword2 <- data_frame(id = c(1 :  length(data_keyword2[,1])  ), 
              keyword = data_keyword2$Keyword) %>% unnest(keyword)

 nasa_keyword2 <-  nasa_keyword2 %>%  unnest_tokens(word, keyword) %>%  anti_join(stop_words)
 
 nasa_keyword2


```





```{r}

 library(widyr)
 title_word_pairs <- nasa_keyword2 %>%
 pairwise_count(word, id, sort = TRUE, upper = FALSE)
 title_word_pairs

```





```{r}
library(ggplot2)
 library(igraph)
 library(ggraph)

 set.seed(1234)
 title_word_pairs %>%
  filter(n >= 3) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = n, edge_width = n), edge_colour = "cyan4") +
  geom_node_point(size = 5) +
  geom_node_text(aes(label = name), repel = TRUE,
                 point.padding = unit(0.2, "lines")) +
  theme_void()
 
 
```























##########Coba data Judol


```{r}
library(readxl)

data_judol <- read_xlsx("judol.xlsx")
data_judol <- as.data.frame(data_judol)
data_judol



```





```{r}


data_judol2 <- data_judol[c("Keyword")]

data_judol3 <- data_judol2

for(i in 1 : length(data_judol2[,1]))
{
  
  x <- data_judol2[i,1]
  
    simpan_keyword_hapus_spasi <- gsub(" ", "", x)
    simpan_keyword_hapus_spasi <- gsub("-", "", simpan_keyword_hapus_spasi)
    simpan_keyword_hapus_spasi <- gsub("'", "", simpan_keyword_hapus_spasi)
    
    data_judol3[i,1] = simpan_keyword_hapus_spasi
    
    
  
  
}


data_judol3
```




```{r}
 library(tidytext)
library(ggplot2)
 library(igraph)
 library(ggraph)
 library(tidyr)


library(dplyr)
library(tidytext)
library(widyr)
 library(tidyr)

library(widyr)

 nasa_judol <- data_frame(id = c(1 :  length(data_judol3[,1])  ), 
              keyword = data_judol3$Keyword ) %>% unnest(keyword)

 nasa_judol <-  nasa_judol %>%  unnest_tokens(word, keyword) %>%  anti_join(stop_words)
 
nasa_judol


```






```{r}

 library(widyr)
 title_word_pairs <- nasa_judol %>%
 pairwise_count(word, id, sort = TRUE, upper = FALSE)
 title_word_pairs

```





```{r}
library(ggplot2)
 library(igraph)
 library(ggraph)

 set.seed(1234)
 title_word_pairs %>%
  filter(n >= 2) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = n, edge_width = n), edge_colour = "cyan4") +
  geom_node_point(size = 5) +
  geom_node_text(aes(label = name), repel = TRUE,
                 point.padding = unit(0.2, "lines")) +
  theme_void()
 
 
```





```{r}

 set.seed(1234)
 title_word_pairs %>%
 filter(n >= 2) %>%
 graph_from_data_frame() %>%
 ggraph(layout = "fr") +
 geom_edge_link(aes(edge_alpha = n, edge_width = n),
 edge_colour = "royalblue") +
 geom_node_point(size = 5) +
 geom_node_text(aes(label = name), repel = TRUE,
 point.padding = unit(0.2, "lines")) +
 theme_void()

```



```{r}
library(igraph)
library(tidygraph)
library(ggraph)


cooccur <-  title_word_pairs

cooccur
```



```{r}

wordnetwork <- head(cooccur, 20)
wordnetwork <- graph_from_data_frame(wordnetwork)
ggraph(wordnetwork, layout = "fr") +
  geom_edge_link(aes(width = n, edge_alpha = n), edge_colour = "#ed9de9") +
  geom_node_point(aes(size = igraph::degree(wordnetwork)), shape = 1, color = "black") +
  geom_node_text(aes(label = name), col = "darkblue", size = 3) +
  labs(title = "Co-occurrences within sentence",
       subtitle = "Top 100 Nouns, Names, Adjectives, Verbs, Adverbs",
       caption = "Surah Yusuf (Saheeh International)")

```






```{r}

wordnetwork <- head(cooccur, 20)
wordnetwork <- graph_from_data_frame(wordnetwork)
ggraph(wordnetwork, layout = "fr") +
  geom_edge_link(aes(width = 1, edge_alpha = 1), edge_colour = "#ed9de9") +
  geom_node_point(aes(size = igraph::degree(wordnetwork)), shape = 1, color = "black") +
  geom_node_text(aes(label = name), col = "darkblue", size = 3) +
  labs(title = "Co-occurrences within sentence",
       subtitle = "Top 100 Nouns, Names, Adjectives, Verbs, Adverbs",
       caption = "Surah Yusuf (Saheeh International)")

```








```{r}

wordnetwork <- head(cooccur, 50)
wordnetwork <- graph_from_data_frame(wordnetwork)
ggraph(wordnetwork, layout = "fr") +
  geom_edge_link(aes(width = 1, edge_alpha = 1), edge_colour = "#ed9de9") +
  geom_node_point(aes(size = igraph::degree(wordnetwork)), shape = 1, color = "black") +
  geom_node_text(aes(label = name), col = "darkblue", size = 3) + theme(legend.position="none")


```






```{r}

wordnetwork <- head(cooccur, 50)
wordnetwork <- graph_from_data_frame(wordnetwork)
ggraph(wordnetwork, layout = "fr") +
  geom_edge_link(aes(width = n, edge_alpha = n), edge_colour = "#ed9de9") +
  geom_node_point(aes(size = igraph::degree(wordnetwork)), shape = 1, color = "black") +
  geom_node_text(aes(label = name), col = "darkblue", size = 3) + theme(legend.position="none")


```





```{r}

wordnetwork <- head(cooccur, 30)
gm1 <- graph_from_data_frame(wordnetwork)
ggraph(gm1, layout = 'kk') + 
      geom_edge_density(aes(fill = n)) + 
      geom_edge_link(alpha = 0.7, color = "#57d3e6") +
      geom_node_point(aes(size = degree(gm1)), colour = "#a83268") +
      geom_node_text(aes(label = name), size = 3, repel=TRUE) +
     theme(legend.position="none")



```




```{r}

ggraph(gm1, layout = 'kk') + 
      geom_edge_density(aes(fill = n)) + 
      geom_edge_link(alpha = 0.7, color = "#57d3e6") +
      geom_node_point(aes(size = degree(gm1)),
                      colour = "#a83268") +   theme(legend.position="none")

```








```{r}

ggraph(gm1, layout = 'linear', circular = TRUE) + 
     geom_edge_arc(color = "orange", width=0.7) +
     geom_node_point(aes(size = degree(gm1)), alpha = igraph::degree(gm1), 
                     colour = "#a83268") +
     geom_node_text(aes(label = name), size = 3, repel=TRUE) +
     theme_void() +
   theme(legend.position="none")

```







```{r}

ggraph(gm1, layout = 'linear', circular = TRUE) + 
     geom_edge_arc(color = "#57d3e6", width=0.7) +
     geom_node_point(aes(size = degree(gm1)), alpha = igraph::degree(gm1), 
                     colour = "#a83268") +
     geom_node_text(aes(label = name), size = 3, repel=TRUE) +
     theme_void() +
   theme(legend.position="none")

```






```{r}

wordnetwork <- head(cooccur, 100)
jg <- graph_from_data_frame(wordnetwork)

ggraph(jg, layout = 'kk') + 
      geom_edge_density(aes(fill = n)) + 
      geom_edge_link(alpha = 0.7, color = "#57d3e6") +
      geom_node_point(aes(size = igraph::degree(jg)), 
                      colour = "#a83268", show.legend = FALSE) +
   theme(legend.position="none")

```







```{r}

wordnetwork <- head(cooccur, 100)
jg <- graph_from_data_frame(wordnetwork)

ggraph(jg, layout = 'auto') + 
      geom_edge_density(aes(fill = n)) + 
      geom_edge_link(alpha = 0.7, color = "#57d3e6") +
      geom_node_point(aes(size = igraph::degree(jg)), 
                      colour = "#a83268", show.legend = FALSE) +
   theme(legend.position="none")

```


































































































































































```{r}
library(readxl)

data_judol <- read_xlsx("judol.xlsx")
data_judol <- as.data.frame(data_judol)
data_judol



```





```{r}


data_judol2 <- data_judol[c("Keyword")]

data_judol3 <- data_judol2

for(i in 1 : length(data_judol2[,1]))
{
  
  x <- data_judol2[i,1]
  
    simpan_keyword_hapus_spasi <- gsub(" ", "", x)
    simpan_keyword_hapus_spasi <- gsub("-", "", simpan_keyword_hapus_spasi)
    simpan_keyword_hapus_spasi <- gsub("'", "", simpan_keyword_hapus_spasi)
    
    data_judol3[i,1] = simpan_keyword_hapus_spasi
    
    
  
  
}


data_judol3
```




```{r}

library(ggplot2)
 library(igraph)
 library(ggraph)



library(dplyr)
library(tidytext)
library(widyr)
 library(tidyr)



 nasa_judol <- data_frame(id = c(1 :  length(data_judol3[,1])  ), 
              keyword = data_judol3$Keyword ) %>% unnest(keyword)

 nasa_judol <-  nasa_judol %>%  unnest_tokens(word, keyword) %>%  anti_join(stop_words)
 
nasa_judol


```






```{r}

 library(widyr)
 title_word_pairs <- nasa_judol %>%
 pairwise_count(word, id, sort = TRUE, upper = FALSE)
 title_word_pairs

library(igraph)
library(tidygraph)
library(ggraph)


cooccur <-  title_word_pairs

```




```{r}
library(ggthemes)
wordnetwork <- head(cooccur, 30)
gm1 <- graph_from_data_frame(wordnetwork)
ggraph(gm1, layout = 'kk') + 
      geom_edge_density(aes(fill = n)) + 
      geom_edge_link(alpha = 0.7, color = "#57d3e6") +
      geom_node_point(aes(size = degree(gm1)), colour = "#a83268") +
      geom_node_text(aes(label = name), size = 3, repel=TRUE) +
     theme(legend.position="none") + theme_classic()



```

























```{r}


library(readxl)

data_paper <- read_xlsx("data_paper.xlsx")
data_paper <- as.data.frame(data_paper)



dat <- data_paper

dat
```



```{r}
 cek_keyword = "financial performance"
    
    simpan_indeks <- vector(mode = "numeric")
    simpan_kata <- vector(mode = "character")
    k = 0
    data_keyword <- dat[,"Keyword"]
    
    for(i in 1 : length(data_keyword))
    {
      
      X <- data_keyword[i]
      
      
      
      X <- tolower(X) #mengubah menjadi huruf kecil
      cek_keyword <- tolower(cek_keyword) #mengubah menjadi huruf kecil
      
      X <- unlist(strsplit(as.character(X), "  ;", fixed = TRUE))
      X <- unlist(strsplit(as.character(X), " ;", fixed = TRUE))
      X <- unlist(strsplit(as.character(X), ";  ", fixed = TRUE))
      X <- unlist(strsplit(as.character(X), "; ", fixed = TRUE))
      X <- unlist(strsplit(as.character(X), ";", fixed = TRUE))
      #X <- unlist(strsplit(as.character(X), ", ", fixed = TRUE))
      #X <- unlist(strsplit(as.character(X), "  ,", fixed = TRUE))
      #X <- unlist(strsplit(as.character(X), " ,", fixed = TRUE))
      #X <- unlist(strsplit(as.character(X), ",", fixed = TRUE))
      
      
      ada_keyword <- cek_keyword %in% X
      
      if(ada_keyword == TRUE)
      {
        k = k + 1
        simpan_indeks[k] = i
        simpan_kata[k] = print(paste(X,collapse='; '))
        
      }
      
    }
    
    
    dframe_indeks_keywords <- data.frame(simpan_indeks, simpan_kata)
    colnames(dframe_indeks_keywords) = c("Nomor Paper", "Kata Kunci")

    
    dframe_indeks_keywords
    

```



```{r}
v <- c('A','B','C','D')
print(v)
print(paste(v,collapse='; '))
print(paste(v))

```







































```{r}

library(readxl)

data_paper <- read_xlsx("data_paper.xlsx")
data_paper <- as.data.frame(data_paper)
data_paper

```



```{r}

levels(as.factor(data_paper[,"Scope"]))

```




```{r}

A <- c("Economy", "Health", "Economy")

which(A == "Economy")

```




#Economy
```{r}

A <- c("Economy", "Health", "Economy", "Religion", "Economy", "Science")

bidang <- c("Economy", "Science")

A %in% bidang

```



```{r}
library(readxl)
data_paper <- read_xlsx("data_paper.xlsx")
data_paper <- as.data.frame(data_paper)
data_paper
```




```{r}
library(readxl)
data_paper <- read_xlsx("data_paper.xlsx")
data_paper <- as.data.frame(data_paper)


library(dplyr)

grup <- group_by(data_paper, `Nama Jurnal`, ISSN)

data_jurnal <- grup %>% summarise(
		freq = n()

)

data_jurnal <- as.data.frame(data_jurnal)

colnames(data_jurnal) = c("Journal", "ISSN", "Number of Articles in Our Database")

data_jurnal

```





```{r}

informasi_jurnal_jumlah_artikel <- vector(mode = "character")

for( i in 1 : length(data_jurnal[,1]))
{
  
  nama <- data_jurnal[i,"Journal"]
  issn <- data_jurnal[i,"ISSN"]
  jumlah <- data_jurnal[i,"Number of Articles in Our Database"]
  informasi_jurnal_jumlah_artikel[i] <- paste0(nama,"-",issn," (",jumlah,")")
  
}

data_jurnal_update <- data.frame(data_jurnal, informasi_jurnal_jumlah_artikel)
colnames(data_jurnal_update) <- c("Journal", "ISSN", "Number of Articles in Our Database", "Information")


data_jurnal_update


```




```{r}
X <- c("As--123 (31)", "Dxc-dfr--115 (45)")


simpan_nama <- ""


for(i in 1 : length(X))
{
a <-  strsplit(X[i], "--")

 simpan_nama[i] <- a[[1]][1]
}


simpan_nama


```



